import { useEffect, useState } from "react";
import AdminLayout from "../../components/AdminLayout";
import { createCategory, deleteCategory, getAdminCategories, updateCategory } from "../../services/adminService";

const empty = { name: "", description: "", imageUrl: "", parentId: "" };
function CategoriesManage() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const load = () => getAdminCategories().then(setItems).catch((err) => setError(err.message));
  useEffect(load, []);
  const submit = async (e) => { e.preventDefault(); const payload = { ...form, parentId: form.parentId ? Number(form.parentId) : null }; try { if (editing) await updateCategory(editing, payload); else await createCategory(payload); setForm(empty); setEditing(null); setOpen(false); load(); } catch (err) { setError(err.message); } };
  const edit = (item) => { setEditing(item.id); setForm({ name: item.name, description: item.description || "", imageUrl: item.imageUrl || "", parentId: item.parentId || "" }); setOpen(true); };
  const remove = async (id) => { if (!window.confirm("Delete this category?")) return; try { await deleteCategory(id); load(); } catch (err) { setError(err.message); } };
  return <AdminLayout title="Categories" eyebrow="Catalog structure" actions={<button className="button" onClick={() => { setOpen(!open); setEditing(null); setForm(empty); }}>{open ? "Close" : "+ Add category"}</button>}>{error && <div className="error-banner">{error}</div>}{open && <form className="admin-card admin-form-grid" onSubmit={submit}><div className="card-heading wide"><div><span className="eyebrow">{editing ? "Edit category" : "New category"}</span><h2>{editing ? form.name : "Create a collection"}</h2></div></div><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Parent<select value={form.parentId} onChange={(e) => setForm({ ...form, parentId: e.target.value })}><option value="">No parent</option>{items.filter((x) => x.id !== editing).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="wide">Description<input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="wide">Image URL<input value={form.imageUrl} onChange={(e) => setForm({ ...form, imageUrl: e.target.value })} /></label><div className="wide"><button className="button">{editing ? "Save category" : "Create category"}</button></div></form>}<div className="category-admin-grid">{items.map((item) => <article className="admin-card category-admin-card" key={item.id}>{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <div className="category-placeholder">{item.name[0]}</div>}<div><span className="eyebrow">{item.parentId ? "Subcategory" : "Top level"}</span><h2>{item.name}</h2><p>{item.description || "No description yet."}</p><div className="row-actions"><button onClick={() => edit(item)}>Edit</button><button className="danger" onClick={() => remove(item.id)}>Delete</button></div></div></article>)}</div></AdminLayout>;
}
export default CategoriesManage;
